import Head from 'next/head'
import CarCard from '@/components/CarCard'
import { ThemePicker, StyleProvider } from 'vcc-ui'

export default function Home() {
  return (
    <StyleProvider>
      <ThemePicker variant="light">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <CarCard id='xc90-recharge' modelName='XC90 Recharge' bodyType='suv' modelType='plug-in hybrid' imageUrl='/images/xc90_recharge.jpg' /> 
        </main>
      </ThemePicker>
    </StyleProvider>
  )
}
