steps:
  - id: 'build-docker'
    waitFor: ['-']
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    env:
      - 'DOCKER_BUILDKIT=1'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        -t ${_IMAGE_NAME}:${COMMIT_SHA} \
        -t ${_IMAGE_NAME}:${_CLEAN_BRANCH_NAME} \
        --cache-from ${_IMAGE_NAME}:${_CLEAN_BRANCH_NAME} \
        --cache-from ${_IMAGE_NAME}:${COMMIT_SHA} \
        --build-arg NEXT_PUBLIC_IMAGE_URL=${_NEXT_PUBLIC_IMAGE_URL} \
        .
  - id: 'push-docker'
    waitFor: ['build-docker']
    name: 'gcr.io/cloud-builders/docker:20.10.14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push ${_IMAGE_NAME}:$COMMIT_SHA
        docker push ${_IMAGE_NAME}:$_CLEAN_BRANCH_NAME

images: ["${_IMAGE_NAME}:$COMMIT_SHA", "${_IMAGE_NAME}:$_CLEAN_BRANCH_NAME"]
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _IMAGE_NAME: eu.gcr.io/${PROJECT_ID}/${REPO_NAME}
  _SERVICE_NAME: car-list-ui
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
  _TRIGGER_ID: 7191c5c6-bd4c-4475-a899-568548874a6d
  _CLEAN_BRANCH_NAME: ${BRANCH_NAME//\//-}
  _NEXT_PUBLIC_IMAGE_URL: http://storage.googleapis.com/volvocars_bucket
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - car-list-ui
